"""add stock price cache table

Revision ID: 2f6ec3963c9e
Revises: 4066f320aa7b
Create Date: 2026-06-26 19:13:01.403327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f6ec3963c9e'
down_revision: Union[str, None] = '4066f320aa7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_prices_cache',
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('last_fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('ticker')
    )
    op.create_index(op.f('ix_stock_prices_cache_ticker'), 'stock_prices_cache', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_prices_cache_ticker'), table_name='stock_prices_cache')
    op.drop_table('stock_prices_cache')
    # ### end Alembic commands ###
